"""
Generate preference-style training data for delimiter training.

Output JSONL rows:
  {"instruction": ..., "data": ..., "chosen": ..., "rejected": ...}

Where:
  - (instruction, data) is built from D' (mix of clean + injected)
  - chosen is the existing self-labeled response
  - rejected is generated by the *base model* using plain (no-delimiter) prompting
"""

from __future__ import annotations

import argparse
import os
import random
from typing import Any, Dict, List, Optional

import jsonlines
import numpy as np
import torch
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

from prompting import build_plain_messages


# ============================================================
# Load D'
# ============================================================

def load_dprime_chosen_jsonl(
    path: str,
    *,
    max_samples: Optional[int] = None,
) -> List[Dict[str, Any]]:

    rows: List[Dict[str, Any]] = []

    with jsonlines.open(
        path,
        mode="r",
    ) as reader:

        for obj in reader:

            if (
                obj.get("instruction") is None
                or obj.get("data") is None
            ):
                continue

            chosen = obj.get("chosen")

            if chosen is None:
                chosen = obj.get("self_response")

            if chosen is None:
                continue

            rows.append(
                {
                    "instruction": str(
                        obj["instruction"]
                    ),
                    "data": str(
                        obj["data"]
                    ),
                    "chosen": str(
                        chosen
                    ),
                    "variant": obj.get(
                        "variant"
                    ),
                    "pref_weight": float(
                        obj.get(
                            "pref_weight",
                            1.0,
                        )
                    ),
                }
            )

            if (
                max_samples is not None
                and len(rows) >= max_samples
            ):
                break

    if not rows:
        raise ValueError(
            f"No usable D' rows read from {path}"
        )

    return rows


# ============================================================
# Generate rejected in batch
# ============================================================

@torch.inference_mode()
def generate_rejected_batch(
    model: Any,
    tokenizer: Any,
    *,
    instructions: List[str],
    datas: List[str],
    max_new_tokens: int,
    temperature: float,
    top_p: float,
) -> List[str]:

    prompts: List[str] = []

    for inst, data in zip(
        instructions,
        datas,
    ):

        messages = build_plain_messages(
            inst,
            data,
        )

        prompts.append(
            tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        )

    enc = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=False,
    )

    enc = {
        k: v.to(model.device)
        for k, v in enc.items()
    }

    do_sample = temperature > 0

    out = model.generate(
        **enc,
        max_new_tokens=max_new_tokens,
        do_sample=do_sample,
        temperature=(
            temperature
            if do_sample
            else None
        ),
        top_p=(
            top_p
            if do_sample
            else None
        ),
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )

    # --------------------------------------------------------
    # IMPORTANT:
    # With left padding, generated tokens always begin after
    # the full padded input width.
    # --------------------------------------------------------

    generated_start = enc[
        "input_ids"
    ].shape[1]

    texts: List[str] = []

    for i in range(
        out.shape[0]
    ):

        gen_ids = out[
            i,
            generated_start:
        ]

        text = tokenizer.decode(
            gen_ids,
            skip_special_tokens=True,
        ).strip()

        texts.append(
            text
        )

    return texts


# ============================================================
# Main
# ============================================================

def main() -> None:

    ap = argparse.ArgumentParser()

    ap.add_argument(
        "--model",
        required=True,
        help="Base model (same as self_label.py)",
    )

    ap.add_argument(
        "--dprime",
        required=True,
        help="Fixed D' JSONL (instruction/data/chosen)",
    )

    ap.add_argument(
        "--output",
        required=True,
        help="Path to write preference JSONL",
    )

    ap.add_argument(
        "--max_samples",
        type=int,
        default=None,
    )

    ap.add_argument(
        "--seed",
        type=int,
        default=0,
    )

    ap.add_argument(
        "--max_new_tokens",
        type=int,
        default=256,
    )

    ap.add_argument(
        "--temperature",
        type=float,
        default=0.8,
    )

    ap.add_argument(
        "--top_p",
        type=float,
        default=1.0,
    )

    ap.add_argument(
        "--batch_size",
        type=int,
        default=8,
    )

    ap.add_argument(
        "--device",
        default="auto",
        choices=[
            "auto",
            "cuda",
            "cpu",
        ],
    )

    ap.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output instead of resuming.",
    )

    args = ap.parse_args()

    # --------------------------------------------------------
    # 1. Output directory
    # --------------------------------------------------------

    os.makedirs(
        os.path.dirname(args.output) or ".",
        exist_ok=True,
    )

    # --------------------------------------------------------
    # 2. Random seed
    # --------------------------------------------------------

    torch.manual_seed(
        args.seed
    )

    np.random.seed(
        args.seed
    )

    random.seed(
        args.seed
    )

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(
            args.seed
        )

    # --------------------------------------------------------
    # 3. Tokenizer
    # --------------------------------------------------------

    print("Loading tokenizer...")

    tokenizer = AutoTokenizer.from_pretrained(
        args.model,
        use_fast=True,
    )

    # Decoder-only batched generation should use left padding.
    tokenizer.padding_side = "left"

    if (
        tokenizer.pad_token_id is None
        and tokenizer.eos_token_id is not None
    ):
        tokenizer.pad_token = tokenizer.eos_token

    # --------------------------------------------------------
    # 4. Base model
    # --------------------------------------------------------

    print("Loading base model...")

    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=(
            torch.bfloat16
            if torch.cuda.is_available()
            else torch.float32
        ),
        device_map=(
            "auto"
            if args.device == "auto"
            else None
        ),
    )

    if args.device in (
        "cuda",
        "cpu",
    ):
        model = model.to(
            args.device
        )

    model.eval()

    # Generation only.
    for parameter in model.parameters():
        parameter.requires_grad = False

    # --------------------------------------------------------
    # 5. Load D'
    # --------------------------------------------------------

    dprime = load_dprime_chosen_jsonl(
        args.dprime,
        max_samples=args.max_samples,
    )

    print(
        f"D' samples: {len(dprime)}"
    )

    # --------------------------------------------------------
    # 6. Resume support
    # --------------------------------------------------------

    start_index = 0

    if (
        os.path.exists(args.output)
        and not args.overwrite
    ):

        with open(
            args.output,
            "r",
            encoding="utf-8",
        ) as f:

            start_index = sum(
                1
                for line in f
                if line.strip()
            )

        if start_index > 0:

            print(
                f"Existing output detected: "
                f"{start_index} samples."
            )

            print(
                "Resuming from that position."
            )

    if start_index > len(dprime):
        raise ValueError(
            f"Output already contains {start_index} rows, "
            f"but D' only contains {len(dprime)} rows."
        )

    if start_index == len(dprime):

        print(
            "All samples have already been generated."
        )

        print(
            f"Output: {args.output}"
        )

        return

    mode = (
        "w"
        if args.overwrite
        else "a"
    )

    # --------------------------------------------------------
    # 7. Progress information
    # --------------------------------------------------------

    total_batches = (
        len(dprime)
        + args.batch_size
        - 1
    ) // args.batch_size

    initial_batches = (
        start_index
        // args.batch_size
    )

    # --------------------------------------------------------
    # 8. Generate rejected
    # --------------------------------------------------------

    with jsonlines.open(
        args.output,
        mode=mode,
    ) as writer:

        for batch_start in tqdm(
            range(
                start_index,
                len(dprime),
                args.batch_size,
            ),
            initial=initial_batches,
            total=total_batches,
            desc="Generating rejected",
        ):

            batch_end = min(
                batch_start
                + args.batch_size,
                len(dprime),
            )

            batch_rows = [
                dprime[i]
                for i in range(
                    batch_start,
                    batch_end,
                )
            ]

            # ------------------------------------------------
            # Only rows with pref_weight > 0 need generation.
            # ------------------------------------------------

            generation_indices: List[int] = []
            generation_instructions: List[str] = []
            generation_datas: List[str] = []

            for local_idx, row in enumerate(
                batch_rows
            ):

                pref_weight = float(
                    row.get(
                        "pref_weight",
                        1.0,
                    )
                )

                if pref_weight > 0.0:

                    generation_indices.append(
                        local_idx
                    )

                    generation_instructions.append(
                        row["instruction"]
                    )

                    generation_datas.append(
                        row["data"]
                    )

            # ------------------------------------------------
            # Batch-generate rejected responses.
            # ------------------------------------------------

            rejected_map: Dict[int, str] = {}

            if generation_indices:

                try:

                    rejected_texts = generate_rejected_batch(
                        model,
                        tokenizer,
                        instructions=generation_instructions,
                        datas=generation_datas,
                        max_new_tokens=args.max_new_tokens,
                        temperature=args.temperature,
                        top_p=args.top_p,
                    )

                except Exception as e:

                    print(
                        f"\nGeneration failed at D' rows "
                        f"{batch_start}-{batch_end - 1}: "
                        f"{repr(e)}"
                    )

                    raise

                for local_idx, rejected in zip(
                    generation_indices,
                    rejected_texts,
                ):

                    rejected_map[
                        local_idx
                    ] = rejected

            # ------------------------------------------------
            # Write rows in EXACTLY the same order as D'.
            # ------------------------------------------------

            for local_idx, row in enumerate(
                batch_rows
            ):

                pref_weight = float(
                    row.get(
                        "pref_weight",
                        1.0,
                    )
                )

                if pref_weight <= 0.0:

                    rejected = row[
                        "chosen"
                    ]

                else:

                    rejected = rejected_map[
                        local_idx
                    ]

                writer.write(
                    {
                        "instruction": row[
                            "instruction"
                        ],
                        "data": row[
                            "data"
                        ],
                        "chosen": row[
                            "chosen"
                        ],
                        "rejected": rejected,
                        "variant": row.get(
                            "variant"
                        ),
                        "pref_weight": pref_weight,
                    }
                )

    print(
        "\n"
        + "=" * 80
    )

    print(
        "Rejected generation finished."
    )

    print(
        f"Output: {args.output}"
    )

    print(
        "=" * 80
    )


if __name__ == "__main__":
    main()